from typing import Optional, Any, List
from api.src.backend.entities import MinerAgent

async def get_latest_agent(miner_hotkey: str) -> Optional[MinerAgent]: ...
async def get_agent_by_version_id(version_id: str) -> Optional[MinerAgent]: ...
async def get_agents_awaiting_screening() -> List[MinerAgent]: ...
async def check_if_agent_banned(miner_hotkey: str) -> bool: ...
async def get_top_agent() -> dict[str, Any]: ...
async def ban_agent(miner_hotkey: str) -> None: ...
async def approve_agent_version(version_id: str) -> None: ...