from datetime import datetime
from typing import Optional, List, Tuple
from api.src.backend.entities import MinerAgent
from api.src.utils.models import TopAgentHotkey

async def get_latest_agent(miner_hotkey: str) -> Optional[MinerAgent]: ...
async def get_agent_by_version_id(version_id: str) -> Optional[MinerAgent]: ...
async def get_agent_approved_banned(version_id: str, miner_hotkey: str) -> Tuple[Optional[datetime], bool]: ...
async def check_if_agent_banned(miner_hotkey: str) -> bool: ...
async def get_top_agent() -> Optional[TopAgentHotkey]: ...
async def get_agents_by_hotkey(miner_hotkey: str) -> List[MinerAgent]: ...
async def ban_agents(miner_hotkeys: List[str], reason: str) -> None: ...
async def approve_agent_version(version_id: str) -> None: ...
async def set_approved_agents_to_awaiting_screening() -> List[MinerAgent]: ...
async def get_all_approved_version_ids() -> List[str]: ...