from typing import Optional
from api.src.backend.entities import MinerAgent

async def get_agent_by_hotkey(miner_hotkey: str) -> Optional[MinerAgent]: ...
async def store_agent(agent: MinerAgent) -> None: ...