from typing import List, Optional
from api.src.backend.entities import EvaluationsWithHydratedRuns, Evaluation, EvaluationsWithHydratedUsageRuns

async def get_evaluation_by_evaluation_id(evaluation_id: str) -> Evaluation: ...
async def get_evaluations_by_version_id(version_id: str) -> List[Evaluation]: ...
async def get_evaluations_for_agent_version(version_id: str, set_id: Optional[int] = None) -> list[EvaluationsWithHydratedRuns]: ...
async def get_evaluations_with_usage_for_agent_version(version_id: str, set_id: Optional[int] = None) -> list[EvaluationsWithHydratedUsageRuns]: ...
async def get_running_evaluations() -> List[Evaluation]: ...
async def get_running_evaluation_by_validator_hotkey(validator_hotkey: str) -> Optional[Evaluation]: ...
async def get_running_evaluation_by_miner_hotkey(miner_hotkey: str) -> Optional[Evaluation]: ...
async def does_validator_have_running_evaluation(validator_hotkey: str) -> bool: ...
async def get_queue_info(validator_hotkey: str, length: int = 10) -> List[Evaluation]: ...
async def get_agent_name_from_version_id(version_id: str) -> Optional[str]: ...
async def get_miner_hotkey_from_version_id(version_id: str) -> Optional[str]: ...