from api.src.backend.entities import OpenUser
from typing import Optional
from datetime import datetime

async def get_open_user(auth0_user_id: str) -> OpenUser: ...
async def create_open_user(open_user: OpenUser) -> None: ...
async def get_open_user_by_hotkey(open_hotkey: str) -> Optional[OpenUser]: ...
async def check_open_user_email_in_whitelist(email: str) -> bool: ...
async def add_open_user_email_to_whitelist(email: str) -> None: ...
async def get_open_user_by_email(email: str) -> Optional[OpenUser]: ...
async def update_open_user_bittensor_hotkey(open_hotkey: str, bittensor_hotkey: str) -> None: ...
async def get_open_user_bittensor_hotkey(open_hotkey: str) -> Optional[str]: ...
async def get_open_agent_periods_on_top(miner_hotkey: str, hours: float) -> list[tuple[datetime, datetime]]: ...
async def get_emission_dispersed_to_open_user(open_hotkey: str) -> int: ...