from api.src.backend.entities import OpenUser
from typing import Optional

async def get_open_user(auth0_user_id: str) -> OpenUser: ...
async def create_open_user(open_user: OpenUser) -> None: ...
async def get_open_user_by_hotkey(open_hotkey: str) -> Optional[OpenUser]: ...