from api.src.backend.entities import OpenUser
from typing import Optional
from datetime import datetime

async def get_open_user(auth0_user_id: str) -> OpenUser: ...
async def create_open_user(open_user: OpenUser) -> None: ...
async def get_open_user_by_hotkey(open_hotkey: str) -> Optional[OpenUser]: ...

async def get_open_user_by_email(email: str) -> Optional[OpenUser]: ...
async def update_open_user_bittensor_hotkey(open_hotkey: str, bittensor_hotkey: str) -> None: ...
async def get_open_user_bittensor_hotkey(open_hotkey: str) -> Optional[str]: ...
async def get_open_agent_periods_on_top(miner_hotkey: str) -> list[tuple[datetime, datetime]]: ...
async def get_periods_on_top_map() -> dict[str, list[tuple[datetime, datetime]]]: ...
async def get_emission_dispersed_to_open_user(open_hotkey: str) -> int: ...
async def get_treasury_transactions_for_open_user(open_hotkey: str) -> list[dict]: ...
async def get_all_transactions(open_hotkey: str) -> list[dict]: ...
async def get_all_treasury_hotkeys() -> list[dict]: ...
async def get_total_dispersed_by_treasury_hotkeys() -> int: ...
async def get_total_payouts_by_version_ids(version_ids: list[str]) -> dict[str, int]: ...