from api.src.backend.entities import TreasuryTransaction

async def check_for_new_high_score(version_id: str) -> dict: ...
async def get_treasury_hotkeys() -> list[str]: ...
async def store_treasury_transaction(transaction: TreasuryTransaction): ...