from api.src.backend.entities import TreasuryTransaction

async def check_for_new_high_score(version_id: str) -> dict: ...
async def get_treasury_hotkeys() -> list[str]: ...
async def store_treasury_transaction(transaction: TreasuryTransaction): ...
async def generate_threshold_function() -> str: ...
async def evaluate_agent_for_threshold_approval(version_id: str, set_id: int) -> dict: ...