from typing import Optional, List
from api.src.utils.models import WeightsData

async def store_weights(miner_weights: dict, time_since_last_update=None) -> int: ...
async def get_latest_weights() -> Optional[dict]: ...
def weights_are_different(current_weights: dict, stored_weights: dict) -> bool: ...
async def get_weights_history_last_24h_with_prior() -> List[WeightsData]: ... 